import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import axiosInstance from "../api/axiosInstance";

export default function AlumniPage() {
  const [highlights, setHighlights] = useState([]);
  useEffect(() => { axiosInstance.get("/community").then((response) => setHighlights(response.data.highlights || [])).catch(() => {}); }, []);
  const alumni = highlights.filter((item) => item.category === "alumni");
  const hallOfFame = highlights.filter((item) => item.category === "hall_of_fame");
  return <main className="min-h-screen bg-[#fdf6e3] px-6 py-12 text-[#2c1a11] sm:px-10"><div className="mx-auto max-w-5xl"><Link to="/" className="text-sm font-bold text-amber-800">Back to ASTU MSJ</Link><header className="py-20"><p className="text-xs uppercase tracking-[0.3em] text-amber-700">Beyond the bootcamp</p><h1 className="mt-4 text-5xl font-extrabold sm:text-6xl">Alumni & Hall of Fame</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-[#5d4638]">A public celebration of graduates and approved community achievements.</p></header><section className="grid gap-5 md:grid-cols-3" aria-label="Hall of Fame">{hallOfFame.length ? hallOfFame.map((item) => <article key={item._id} className="rounded-2xl bg-[#2c1a11] p-6 text-[#fdf6e3] md:col-span-1"><p className="text-xs uppercase tracking-widest text-[#d8b493]">Hall of Fame</p><h2 className="mt-3 text-xl font-bold">{item.name}</h2><p className="mt-3 text-sm leading-relaxed text-[#ead9ca]">{item.detail}</p>{item.achievement && <p className="mt-3 text-xs text-[#d8b493]">{item.achievement}</p>}</article>) : <div className="rounded-2xl bg-[#2c1a11] p-6 text-[#fdf6e3] md:col-span-3"><p className="text-sm text-[#ead9ca]">Hall of Fame highlights will appear here after admin approval.</p></div>}</section><section className="mt-10"><h2 className="text-3xl font-bold">Alumni community</h2><div className="mt-5 grid gap-5 md:grid-cols-3">{alumni.map((item) => <article key={item._id} className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#d8b493] text-xl font-bold">{item.name.charAt(0)}</div><h2 className="mt-5 font-bold">{item.name}</h2><p className="mt-2 text-sm leading-relaxed text-gray-600">{item.detail}</p>{item.cohort && <p className="mt-3 text-xs text-amber-700">Cohort {item.cohort}</p>}</article>)}</div></section><p className="mt-12 text-sm text-[#5d4638]">Interested in joining the next chapter? <Link to="/signup" className="font-bold text-amber-800 underline">Start your application</Link>.</p></div></main>;
}
