import { Link } from "react-router-dom";

const alumni = [
  { name: "ASTU MSJ Alumni Network", detail: "A growing community of bootcamp graduates building with confidence." },
  { name: "Community Builders", detail: "Alumni who continue sharing projects, ideas, and opportunities." },
  { name: "Future Makers", detail: "Learners carrying the bootcamp spirit into their next chapter." },
];

export default function AlumniPage() {
  return <main className="min-h-screen bg-[#fdf6e3] px-6 py-12 text-[#2c1a11] sm:px-10"><div className="mx-auto max-w-5xl"><Link to="/" className="text-sm font-bold text-amber-800">Back to ASTU MSJ</Link><header className="py-20"><p className="text-xs uppercase tracking-[0.3em] text-amber-700">Beyond the bootcamp</p><h1 className="mt-4 text-5xl font-extrabold sm:text-6xl">Alumni & Hall of Fame</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-[#5d4638]">A public celebration of the people and community growing through the ASTU MSJ Bootcamp.</p></header><section className="grid gap-5 md:grid-cols-3" aria-label="Alumni community"><div className="rounded-2xl bg-[#2c1a11] p-6 text-[#fdf6e3] md:col-span-2"><p className="text-xs uppercase tracking-widest text-[#d8b493]">Hall of Fame</p><h2 className="mt-3 text-3xl font-bold">Celebrating progress that lasts</h2><p className="mt-4 max-w-xl leading-relaxed text-[#ead9ca]">The Hall of Fame is reserved for future graduate highlights, standout projects, and community contributions approved for public display.</p></div><div className="rounded-2xl border border-[#d8b493] bg-[#ede0d4] p-6"><p className="text-xs uppercase tracking-widest text-amber-700">Alumni</p><p className="mt-3 text-4xl font-extrabold">2026</p><p className="mt-2 text-sm text-[#5d4638]">The beginning of an ongoing learning network.</p></div></section><section className="mt-10 grid gap-5 md:grid-cols-3">{alumni.map((item) => <article key={item.name} className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#d8b493] text-xl font-bold">{item.name.charAt(0)}</div><h2 className="mt-5 font-bold">{item.name}</h2><p className="mt-2 text-sm leading-relaxed text-gray-600">{item.detail}</p></article>)}</section><p className="mt-12 text-sm text-[#5d4638]">Interested in joining the next chapter? <Link to="/signup" className="font-bold text-amber-800 underline">Start your application</Link>.</p></div></main>;
}
