import React, { useState } from "react";
import axios from "axios";
import { useLocation, useNavigate } from "react-router-dom";
const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5000/api";
const input = "w-full rounded-xl border border-[#4a3b32] bg-transparent px-4 py-3 text-sm focus:border-[#c89b7b] focus:outline-none";
export default function ResetPasswordPage() {
  const query = new URLSearchParams(useLocation().search); const [email, setEmail] = useState(query.get("email") || ""); const [otp, setOtp] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  const submit = async e => { e.preventDefault(); setLoading(true); setMessage(""); try { const r = await axios.post(`${API_URL}/auth/reset-password`, { email, otp, password, confirmPassword }); setMessage(r.data.message); setTimeout(() => navigate("/login"), 1200); } catch (err) { setMessage(err.response?.data?.message || "Reset failed."); } finally { setLoading(false); } };
  return <div className="flex h-screen items-center justify-center bg-[#c89b7b] font-serif"><div className="w-[90vw] max-w-md rounded-3xl bg-[#1e1713] p-8 text-[#f5efe6] shadow-2xl"><h1 className="text-2xl font-bold">Enter OTP</h1>{message && <p className="mt-4 rounded-xl bg-[#16110e] p-3 text-sm text-amber-400">{message}</p>}<form onSubmit={submit} className="mt-5 space-y-3"><input required type="email" value={email} onChange={e => setEmail(e.target.value)} className={input} placeholder="Email"/><input required inputMode="numeric" maxLength={6} value={otp} onChange={e => setOtp(e.target.value.replace(/\D/g, ""))} className={input} placeholder="6-digit OTP"/><input required minLength={6} type="password" value={password} onChange={e => setPassword(e.target.value)} className={input} placeholder="New password"/><input required minLength={6} type="password" value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} className={input} placeholder="Confirm new password"/><button disabled={loading} className="w-full rounded-xl bg-[#c89b7b] py-3 text-sm font-bold text-[#1e1713]">{loading ? "Resetting..." : "Reset Password"}</button></form></div></div>;
}
