import React, { useEffect, useState } from "react";
import axiosInstance from "../api/axiosInstance";

export default function StudentDashboard(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{axiosInstance.get("/students/dashboard").then(r=>setData(r.data.dashboard)).catch(e=>setError(e.response?.data?.message||"Could not load dashboard.")).finally(()=>setLoading(false));},[]);
 if(loading)return <p className="text-[#a39081]">Loading your dashboard...</p>;
 if(error)return <p className="rounded-xl border border-rose-900 bg-[#1e1713] p-4 text-rose-300">{error}</p>;
 const d=data; const mentor=d.student.mentor;
 return <div className="space-y-7"><div><h1 className="text-3xl font-extrabold tracking-wide">My Performance Overview</h1><p className="text-xs text-[#a39081]">Your dashboard is loaded from your account, attendance and progress records.</p></div><div className="grid grid-cols-1 md:grid-cols-3 gap-6"><div className="bg-[#1e1713] border border-[#4a3b32] p-6 rounded-2xl"><p className="text-xs text-[#a39081]">Overall Attendance</p><p className="text-2xl font-bold text-[#c89b7b] mt-1">{d.attendancePercentage}%</p></div><div className="bg-[#1e1713] border border-[#4a3b32] p-6 rounded-2xl"><p className="text-xs text-[#a39081]">Completed Topics</p><p className="text-2xl font-bold text-[#c89b7b] mt-1">{d.completedTopics} / {d.totalTopics}</p></div><div className="bg-[#1e1713] border border-[#4a3b32] p-6 rounded-2xl"><p className="text-xs text-[#a39081]">Assigned Mentor</p><p className="text-2xl font-bold text-[#c89b7b] mt-1">{mentor?.fullName||"Not assigned"}</p></div></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><section className="bg-[#1e1713] border border-[#4a3b32] p-6 rounded-2xl"><h2 className="font-bold">My Information</h2><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><p><span className="text-[#a39081]">Name:</span> {d.student.fullName}</p><p><span className="text-[#a39081]">Email:</span> {d.student.email}</p><p><span className="text-[#a39081]">Department:</span> {d.student.department||"—"}</p><p><span className="text-[#a39081]">Year:</span> {d.student.yearOfStudy||"—"}</p></div></section><section className="bg-[#1e1713] border border-[#4a3b32] p-6 rounded-2xl"><h2 className="font-bold">Progress</h2><div className="mt-4 space-y-2">{d.progress.length?d.progress.map(p=><div key={p._id} className="flex justify-between rounded-xl border border-[#4a3b32] p-3 text-sm"><span>{p.topic}</span><span className="text-[#c89b7b]">{p.status}</span></div>):<p className="text-xs text-[#a39081]">No progress records yet.</p>}</div></section></div></div>;
}
