const express = require("express");
const { register, login, forgotPassword, resetPassword, changePassword, me } = require("./authController");
const protect = require("../../middleware/authMiddleware");
const router = express.Router();
router.post("/register", register);
router.post("/login", login);
router.post("/forgot-password", forgotPassword);
router.post("/reset-password", resetPassword);
router.post("/change-password", protect, changePassword);
router.get("/me", protect, me);
module.exports = router;
