export const navigationConfig = {
  admin: [
    { name: "Dashboard", path: "/admin/dashboard" },
    { name: "User Management", path: "/admin/users" },
    { name: "Batches", path: "/admin/batches" },
    { name: "Assignments", path: "/admin/assignments" },
    { name: "Sessions", path: "/sessions" },
    { name: "Coding Challenges", path: "/admin/coding" },
    // { name: "Notifications", path: "/notifications" },
    { name: "Announcements", path: "/admin/announcements" },
    // { name: "Settings", path: "/settings" },
  ],
  mentor: [
    { name: "Dashboard", path: "/mentor/dashboard" },
    { name: "Attendance", path: "/mentor/attendance" },
    { name: "Progress Tracker", path: "/mentor/progress" },
    { name: "Assignments & Grading", path: "/mentor/assignments" },
    { name: "Sessions", path: "/sessions" },
    { name: "Coding Progress", path: "/mentor/coding" },
    { name: "Announcements", path: "/mentor/announcements" },
  ],
  student: [
    { name: "Dashboard", path: "/student/dashboard" },
    { name: "My Attendance", path: "/student/attendance" },
    { name: "Assignments", path: "/student/assignments" },
    { name: "Sessions", path: "/sessions" },
    { name: "Resources", path: "/student/resources" },
    { name: "Announcements", path: "/student/announcements" },
  ],
};
